language: objective-c
osx_image: xcode7.2

env:
  global:
    - PROJECT="Support/HockeySDK.xcodeproj"
    - SDK="appletvsimulator"
    - CONFIGURATION="DEBUG"

  matrix:
#    - SCHEME="HockeySDK"             DESTINATION="OS=9.0,name=Apple TV 1080p"                   RUN_TESTS="YES"
    - SCHEME="HockeySDK"             DESTINATION="OS=9.1,name=Apple TV 1080p"                   RUN_TESTS="YES"
#    - SCHEME="HockeySDK"             DESTINATION="OS=9.2,name=Apple TV 1080p"                   RUN_TESTS="YES"
    - SCHEME="HockeySDK Framework"   DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p"  RUN_TESTS="YES"
    - SCHEME="HockeySDK Distribution"                                                           RUN_TESTS="NO"

before_install:
  - xcrun simctl list
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - brew tap homebrew/versions
  - brew install appledoc22
  - brew link --force appledoc22

script:
  - set -o pipefail
  - COMMAND="xcodebuild -project '$PROJECT' -scheme '$SCHEME' -sdk '$SDK' -configuration '$CONFIGURATION'"
  - if [ $RUN_TESTS == "YES" ]; then
      COMMAND+=" -destination '$DESTINATION' XCODEBUILD_GCC_PREPROCESSOR_DEFINITIONS="CI=1" clean test";
    fi
  - COMMAND+=" | xcpretty -c"
  - echo $COMMAND
  - eval $COMMAND
